MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "../resnet101-5d3b4d8f.pth"
  CUDADEVICE: "0"
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256

#  ROI_BOX_HEAD:
#    POOLER_RESOLUTION: 3
#    POOLER_SCALES: (0.125, 0.0625, 0.03125, 0.015625, 0.0078125)
#    POOLER_SAMPLING_RATIO: 2
#    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
#    PREDICTOR: "FPNPredictor"
  RETINANET:
    USE_C5: False
    ANCHOR_SIZES: (15, 30, 55, 105)
    ANCHOR_STRIDES: (8, 16, 32, 64)
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: -1
    FG_IOU_THRESHOLD: 0.45
    BG_IOU_THRESHOLD: 0.4
    INFERENCE_TH: 0.5

DATASETS:
  TRAIN: ("lym_train1", )
  TEST: ("lym_test1",)
INPUT:
  MIN_SIZE_TRAIN: (320, )
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 320
DATALOADER:
  SIZE_DIVISIBILITY: 6

SOLVER:
  BASE_LR: 0.001
  GAMMA: 0.1
  WEIGHT_DECAY: 0.01
  STEPS: (10000, 15000)
  MAX_ITER: 20000

  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
TEST:
  IMS_PER_BATCH: 4
OUTPUT_DIR: "../outputs/RetinaNet/lymdata-LR0.001SGD-WEIGHT_DECAY0.01-GPUbatch4-epoch1000"



